export const progress = [
    {
        date: '12-06-2019',
        weight: '75kg',
        neck: '30cm',
        chest: '101cm',
        calf: '30cm',
        hips: '76cm',
        weightP: '- 3.5kg',
        neckP: '+ 3cm',
        chestP: '+ 2cm',
        calfP: '+ 2cm',
        hipsP: '+ 2.5cm',
    },
    {
        date: '05-03-2019',
        weight: '76kg',
        neck: '29cm',
        chest: '100cm',
        calf: '29cm',
        hips: '75cm',
        weightP: '- 2.5kg',
        neckP: '+ 2cm',
        chestP: '+ 1cm',
        calfP: '+ 1cm',
        hipsP: '+ 1.5cm',
    },
    {
        date: '28-12-2018',
        weight: '77kg',
        neck: '28cm',
        chest: '99cm',
        calf: '28.5cm',
        hips: '74m',
        weightP: '- 1.5kg',
        neckP: '+ 1cm',
        chestP: ' 0cm',
        calfP: '+ 0.5cm',
        hipsP: '+ 0.5cm',
    },
    {
        date: '14-08-2018',
        weight: '78kg',
        neck: '27cm',
        chest: '99cm',
        calf: '28.5cm',
        hips: '73.5m',
        weightP: '- 0.5kg',
        neckP: ' 0cm',
        chestP: ' 0cm',
        calfP: '+ 0.5cm',
        hipsP: ' 0cm',
    },
];
